import Header from './header/page';


export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
};

export default function RootLayout({ children }) {
    
  return (
    <html lang="en">
      <head>
        <title>{metadata.title}</title>
        <meta name="description" content={metadata.description} />
        {/* Add any other meta tags or links to external stylesheets here */}
      </head>
      <body>
        {children}
      </body>
    </html>
  );
}
